### PR TITLE
Upgrade bouncycastle to 1.62. Fixed #143

### LINKED ISSUE #143: org.bouncycastle:bcprov-jdk15on vulnerability detected
Hi folks,

From: https://snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-32412 

>Affected versions of this package are vulnerable to Unexpected Code Execution via the XMSS/XMSS^MT private key deserialization. A handcrafted private key could include references to unexpected classes which would be picked up from the class path for the executing application.

The recommendation is to use 1.60 at least.

This library uses PGPSecretKeyRingCollection(InputStream in) which is deprecated in 1.50-1.51 (https://github.com/bcgit/bc-java/blob/r1rv51/pg/src/main/java/org/bouncycastle/openpgp/PGPSecretKeyRingCollection.java#L48) and removed in 1.60 and 1.62 https://github.com/bcgit/bc-java/blob/r1rv62/pg/src/main/java/org/bouncycastle/openpgp/PGPSecretKeyRingCollection.java

Any chance you could do the adjustment soon?

Thanks

### PR DESCRIPTION
**Pull request by rpalcolea**

### CODE REVIEW

**Comment by rpalcolea** [comment]
Hi @craigwblake . Any chance you could take a look on this one?

**Comment by rpalcolea** [comment]
Hi @craigwblake . Any chance you could take a look on this one?

**Comment by craigwblake** [comment]
Thanks!

**Comment by rpalcolea** [comment]
thank you! hopefully you can release this soon :) have a nice day

**Pull request merged**
