### PR TITLE
fixed #114 #118

### LINKED ISSUE #114: RPM built with gradle-ospackage-plugin produces "cpio: Archive file not in header" error.
Please close this issue.  Stupid typo error.  False alarm.

### PR DESCRIPTION
**Pull request by bvp**
Need for support non-latin filename charset
Also for [gradle-ospackage-plugin](https://github.com/nebula-plugins/gradle-ospackage-plugin/issues/237)

### CODE REVIEW

**Comment by craigwblake** [comment]
Thanks!

**Comment by jandrops** [comment]
Hi,
 
I'm experiencing the same issue that @bvp is trying to fix when using **gradle-ospackage-plugin**.

Any idea if there is going to be a release soon that contains the fix merged above?

Thanks

**Comment by bvp** [comment]
@jandrops waiting for a new redline release too

**Comment by bvp** [comment]
@craigwblake when will you be able to publish the new version?

**Comment by craigwblake** [comment]
Just released 1.2.6

**Comment by bvp** [comment]
Thank you 👍

**Pull request merged**
